name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
